### ISSUE TITLE
执行 lintFull 后，提示没有发现错误

### ISSUE THREAD

**Issue by LZY101724** [RocketZLY/AndroidLint#1]
根据提供的文档对接到自己的项目后，执行 lintFull 后，提示没有有发现错误，实际实时扫描是有两个错误，如下图：

![lint](https://user-images.githubusercontent.com/22269028/92907455-ee907c80-f457-11ea-8618-04568b8d2802.png)

我的AS环境：
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
classpath "com.android.tools.build:gradle:3.5.3"

**Comment by RocketZLY** [comment]
看看生成的html报告有错误么
![image](https://user-images.githubusercontent.com/13671482/92991976-cc5f3300-f519-11ea-9335-03cd83cb8028.png)
如果没有的话，贴一下custom_lint_config.json配置文件和app下build.gradle文件

**Comment by LZY101724** [comment]
在浏览器查看html报告如下：
![image](https://user-images.githubusercontent.com/22269028/93036738-43f4a580-f673-11ea-8075-89eb67171ce8.png)
custom_lint_config.json文件是从demo里拷贝过来的：
![image](https://user-images.githubusercontent.com/22269028/93037966-4e646e80-f676-11ea-8177-b6ef73aff7ee.png)
下面是我app下的build.gradle：
apply plugin: 'com.android.application'
apply plugin: "com.rocketzly.lintPlugin"

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.1"

    signingConfigs {
        release {
            v1SigningEnabled true
            v2SigningEnabled true
            storeFile file("../key/test.jks")
            storePassword "test123"
            keyAlias "test123"
            keyPassword "test123"
        }
    }

    defaultConfig {
        applicationId "com.example.testgitlabrunnerci"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.release
    }

    buildTypes {
        debug {
            zipAlignEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        release {
            zipAlignEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

    }

    flavorDimensions "default"
    productFlavors {
        gitlab
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

}

**Comment by RocketZLY** [comment]
看不出问题，你方便加下我微信么，微信号：RocketZly，直接沟通应该会快些

**Comment by RocketZLY** [comment]
先给出解决方案：
将androidx.appcompat:appcompat降级为1.1.0，androidx.constraintlayout:constraintlayout降级为1.1.3。

在来说下原因：
我debug了一遍流程发现是androidx.appcompat:appcompat:1.2.0的问题，这个版本代码中加上了一个用来扫描appCompat的lint.jar，但他没有按lint的规范指定IssueRegister的入口，导致LintTask在执行的时候发现了appCompat的lint.jar认为有自定义规则，但是又没找到IssueRegister入口于是认为有问题，停止继续加载其他自定义规则，然后我的自定义规则正好在他后面就被丢弃了。
那现在最好解决方案是先降级appCompat到1.1.0（包括所有依赖了appCompat的第三方库），然后我去给google提个issue，等待他的修复。
