### ISSUE TITLE
增量 lint 检查的参数方便详细介绍一下吗

### ISSUE THREAD

**Issue by gdutxiaoxu** [RocketZLY/AndroidLint#2]
执行 ./gradlew :app:lintIncrement -Pbaseline="dev" -Prevision="HEAD" -PscriptPath="lintNotification.py"

提醒没有错误

**Comment by LZY101724** [comment]
应该是agp3.6以下的那个兼容性bug导致自定义lint丢失的问题，我这边也遇到那个问题了，目前作者正在修这个问题。

**Comment by RocketZLY** [comment]
增量扫描原理是通过git diff $baseline $revision --name-only --diff-filter=ACMRTUXB 去找到变更文件的，所以只要是git命令支持的都可以作为baseline和revision的入参。

**Comment by RocketZLY** [comment]
至于lint没有提示错误，是由于androidx的库引起的，具体原因可以看这个
https://issuetracker.google.com/issues/168848325
目前我已经修复了，等我最新版发布就好了

**Comment by RocketZLY** [comment]
最新版已发布，在com.rocketzly:lintPlugin:0.0.7修复了该问题
