### ISSUE TITLE
在依赖的module里执行lintFull报错

### ISSUE THREAD

**Issue by LZY101724** [RocketZLY/AndroidLint#3]
报错信息如下：
![1224D0CA-A31D-4835-87E9-8E07C097922D](https://user-images.githubusercontent.com/22269028/95548706-3e06a000-0a38-11eb-9e24-e41834262248.png)

经过调试自定义的gradle发现报错的代码位置如下：
![image](https://user-images.githubusercontent.com/22269028/95548817-75754c80-0a38-11eb-8456-b42c4529889d.png)

修改后不再报错，代码如下：
![image](https://user-images.githubusercontent.com/22269028/95559377-38b25100-0a4a-11eb-8cf6-7f7a4e5883e4.png)

**Comment by RocketZLY** [comment]
已修复👍

**Comment by RocketZLY** [comment]
com.rocketzly:lintPlugin:0.0.7已修复该问题
